@startuml
title Smart Home Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы умный дом")
System(smartHome, "SmartHome System", "Система управления умным домом")

System_Ext(heating, "Heating system", "Система отопления")
System_Ext(tempSensor, "Temperature sensor", "Датчик температуры")

Rel(user, smartHome, "Использует систему")
Rel(smartHome, heating, "Управляет отоплением")
Rel(smartHome, tempSensor, "Считывает температуру")

@enduml